server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nguyenducmy199x/lazada-clients-config.git
          clone-on-start: true
          default-label: master
          search-paths: lazada
